database:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "root123"
  database: "PilotOS_DB"

# docker:
#   image: "pilotos/backend:3.18"
#   container_name: "pilotos-service"
#   app_port: 8080
